
= Heat Transfer: Swift

This example shows how to run the heat transfer ADIOS pipeline from Swift.

== Setup

. http://swift-lang.github.io/swift-t/guide.html#_installation[Install Swift/T]
+
NOTE: see <<spack,below>> to build Swift-T combined with Spack.

. Install the https://bitbucket.org/jmjwozniak/mpix_launch_swift[MPIX_Launch library]
+
----
git clone --recursive https://bitbucket.org/jmjwozniak/mpix_launch_swift.git
cd mpix_launch_swift/mpix_launch
make CC=mpicc ENABLE_SHARED=1
cd ../src
./build.sh
----

. Install http://www.cc.gatech.edu/systems/projects/EVPath/[EVPath] (for Flexpath)
+
[NOTE]
====
`bison`, `flex`, `perl` and `cmake` (version > 2.8.3) is required. You can install `perl` and `cmake` with spack. See <<spack,below>> for details.
----
spack install perl cmake
spack load perl cmake
----
====
+
Then, we can start building:
+
----
wget http://www.cc.gatech.edu/systems/projects/EVPath/chaos_bootstrap.pl
perl ./chaos_bootstrap.pl -i
----
+
Then, edit `chaos_build_config` to change install location, etc.
+
----
mkdir -p /dir/to/install
perl ./chaos_build.pl
----
+
NOTE: You may see a few fail messages on pds, gs, or nnti but it is ok to continue.

. Install ADIOS
+
----
wget http://users.nccs.gov/~pnorbert/adios-1.11.0.tar.gz
tar xfz adios-1.11.0.tar.gz
cd adios-1.11.0
./configure --prefix=/dir/to/install --with-flexpath=/dir/to/evpath
make
make install
----
[NOTE]
====
If you have any error related on linking, you need to give additional options with LIBS in configure
----
./configure --prefix=/dir/to/install --with-flexpath=/dir/to/evpath LIBS="-lm -lpthread"
----
====

. Build the heat transfer simulator and stager
+
----
make
cd stage_write
make
----
NOTE: Adios's bin directory should be in PATH env.

. Run the workflow
+
Enable the `FLEXPATH` method in +heat_transfer.xml+ (near end of file). 
Then, type
+
----
./run-workflow.sh 20
----
where 20 is the number of MPI processes.   As shown in the workflow, 12 processes are used for the simulation and 2 are used for the stager.
+
[NOTE]
====
1. Check LAUNCH is correctly set to point to mpix_launch_swift in run-workflow.sh
2. export LD_LIBRARY_PATH to include evpath library if you need.
----
export LD_LIBRARY_PATH=/dir/to/evpath:$LD_LIBRARY_PATH
----
====

== Run with compression

To perform compression through Adios, we need to provide additional options for `stager`. The additional options are i) the list of variables to compress and ii) the Adios' compression parameters. For an example, the following options can used in "workflow.swift" (line 17). 

----
arguments2 = split("heat.bp staged.bp FLEXPATH \"\" MPI \"\" \"T,dt\" \"SZ:accuracy=0.001\"", " ");
----

`stager` will compress `T` and `dT` variables with `SZ` method maintaining absolute errors lower than 0.001 (This is SZ's specific parameters. More details can be found in Adios's manual). 

The following line also work for ZFP:
----
arguments2 = split("heat.bp staged.bp FLEXPATH \"\" MPI \"\" \"T,dt\" \"ZFP:accuracy=0.001\"", " ");
----


[NOTE]
====
1. To use with SZ, ADIOS needs to be configured and compiled with SZ library (https://collab.cels.anl.gov/display/ESR/SZ). I.e., Adios needs to be configured:
+
----
./configure --with-sz=/dir/to/sz ...
----

2. As of Adios 1.11.0 release, ZFP is inclued in the Adios distribution.
====

[[spack]]
== Swift-T build with https://github.com/LLNL/spack[Spack]

We can use Spack to build required libraries and build Swift-T with them.

. https://spack.readthedocs.io/en/latest/getting_started.html[Install Spack]
+
To use with Environment Modules, see https://spack.readthedocs.io/en/latest/module_file_support.html[here]. 
Basically, you need to install env module
+
----
yum install environment-modules
----
Or, we can use spack too
+
----
spack install environment-modules
----
and activate it:
+
----
TMP=`tempfile`
echo >$TMP
MODULE_HOME=`spack location --install-dir environment-modules`
MODULE_VERSION=`ls -1 $MODULE_HOME/Modules | head -1`
${MODULE_HOME}/Modules/${MODULE_VERSION}/bin/add.modules <$TMP
cp .bashrc $TMP
echo "MODULE_VERSION=${MODULE_VERSION}" > .bashrc
cat $TMP >>.bashrc
----

. Build required libraries 
+
----
spack install mpich tcl swig zsh
----

. Build JDK and Ant
+
To build JDK and Ant with Spack, we need extra steps.
Bascially, we need to follow instructions 
http://spack.readthedocs.io/en/latest/basic_usage.html#non-downloadable-tarballs[here].
+
Here is a short summary: Go to Java download website and download JDK (e.g., `jdk-8u131-linux-x64.tar.gz`). Then, do as follows:
+
----
mkdir -p $HOME/.spack/manual_mirror/jdk
mv jdk-8u131-linux-x64.tar.gz $HOME/.spack/manual_mirror/jdk/jdk-8u131.tar.gz
spack mirror add manual file://$HOME/.spack/manual_mirror
spack install jdk@8u131 ant ^jdk@8u131
----

. Build Swift-T
+
----
spack load mpich tcl swig zsh jdk ant
git clone https://github.com/swift-lang/swift-t.git
cd swift-t
./dev/build/init-settings.sh
----
+
Edit `dev/build/swift-t-settings.sh`. At a minimum, set the install directory with SWIFT_T_PREFIX. Then, build:
+
----
$ dev/build/build-all.sh
----
+
After sucessful building, add PATH as follows:
+
----
$ export PATH=/path/to/swift-t-install/turbine/bin:${PATH}
$ export PATH=/path/to/swift-t-install/stc/bin:${PATH}
----
