How to build ADIOS + FlexPath for Blues.

1. Install all APT packages
+
 sudo apt-get update
 sudo apt-get -y install gcc g++ gfortran mpich
 sudo apt-get -y install tcl tcl-dev swig zsh ant
 sudo apt-get -y install build-essential autoconf
 sudo apt-get -y install libxml2 libxml2-dev gsoap
 sudo apt-get -y install bison flex
 sudo apt-get -y install cmake subversion git
+

2. Download/install EVPATH/FlexPath
Download EVPATH
+
 mkdir ~/project
 mkdir ~/project/evpath-build
 cd ~/project/evpath-build
 wget http://www.cc.gatech.edu/systems/projects/EVPath/chaos_bootstrap.pl
+
** Create the evpath installation directory in advance, and specify it when running "perl ./chaos_bootstrap.pl -i", such as $HOME/software/evpath
+
----
 mkdir ~/software
 mkdir ~/software/evpath
 perl ./chaos_bootstrap.pl -i
----
+
Edit chaos_build_config to remove the BUILDLIST entries after evpath with a comment (%). Then, build and install EVPATH. EVPath build requires CMake 3.0 or higher.
+
----
 perl ./chaos_build.pl
----
+
