#!/bin/bash

#PBS -N JOB-heat-test
#PBS -A CSC242
#PBS -q debug 
#PBS -l nodes=2
#PBS -j oe

source $MODULESHOME/init/bash

# NOTE: as of 10/26/17, this adios does not support SZ
module load adios/1.12.0 flexpath/1.12

# If using spack, uncomment this and comment out the module load
# spack load adios sz flexpath

cd "$PBS_O_WORKDIR"

aprun -n 12 ./heat_transfer_adios2 heat  4 3  40 50  6 500 &
aprun -n 2 ./stage_write/stage_write heat.bp staged.bp FLEXPATH "" MPI ""
